"$schema" = "node_modules/wrangler/config-schema.json"
name = "lastwar-helper"
main = ".output/server/index.mjs"
compatibility_date = "2025-06-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"

[observability]
enabled = true

# [[kv_namespaces]]
# binding = "CACHE"
# id = "6da1f6efb8d443c399539a19a1487694"
